projects = [
  {
    name: "Proshop",
    github: "https://github.com/koftov/proshop",
    url: "https://koftovproshop.herokuapp.com/",
    show: true,
    description: "Shopping cart built with MERN & Redux",
    tags:
      "#MongoDB #Express #React #Node #Redux #PWA #ReactReduxHooks #Bootstrap",
  },
  {
    name: "Devconnector",
    github: "https://github.com/koftov/devconnector",
    url: "https://koftovdevconnector.herokuapp.com/",
    show: true,
    description: "Social network for developers, built with MERN & Redux",
    tags: "#MongoDB #Express #React #Node #Redux #Bootstrap #PWA",
  },
  {
    name: "Customer Manager",
    github: "https://github.com/koftov/customer-manager",
    url: "http://aharonlubitsch.herokuapp.com/",
    show: true,
    description: "Customer manager app, build with MERN and Typescript",
    tags:
      "#MongoDB #Express #Node #React #Typescript #ContextAPI #ReactHooks #SemanticUI",
  },
  {
    name: "React Social App",
    github: "https://github.com/koftov/reactsocialfrontend",
    url: "https://koftovsocial.netlify.app/",
    show: true,
    description: "Social app using React hooks & use-immer",
    tags: "#React #ContextAPI #Bootstrap",
  },
  {
    name: "Devcamper API",
    github: "https://github.com/koftov/devcamper-api",
    url: "https://koftov-devcamper-api.herokuapp.com/",
    show: true,
    description: "A real world backend for a bootcamp directory app",
    tags: "#MongoDB #Express #Node",
  },
  {
    name: "Instagram Clone",
    github: "https://github.com/koftov/instagram",
    url: "https://koftovinstagram.herokuapp.com",
    show: true,
    description: "Instagram clone, built with MERN",
    tags:
      "#MongoDB #Express #Node #React #ContextAPI #ReactHooks #Formik #Bootstrap",
  },
  {
    name: "Koftov Models",
    github: "https://github.com/koftov/koftov-models",
    url: "https://koftov-models.web.app",
    show: false,
    description:
      "Real used app that i've created for model agent to track models and sessions",
    tags: "#React #Firebase #Firestore #Semantic-UI",
  },
  {
    name: "Koftov Places",
    github: "https://github.com/koftov/koftovplaces",
    url: "https://koftovplaces.web.app",
    show: false,
    description: "Places sharing app, built with MERN",
    tags: "#MongoDB #Express #Node #React #ContextAPI #ReactHooks",
  },
  {
    name: "Koftov Clothing",
    github: "https://github.com/koftov/koftov-clothing",
    url: "https://koftov-clothing.herokuapp.com/",
    show: false,
    description: "Clothing shop using React & Redux with firebase server",
    tags: "#Firebase #Firestore #Stripe #React #Redux",
  },
  {
    name: "Contact Keeper",
    github: "https://github.com/koftov/contact-keeper",
    url: "https://koftovcontactkeeper.herokuapp.com/",
    show: false,
    description: "Contact manager app, build with MERN",
    tags: "#MongoDB #Express #Node #React #ContextAPI #ReactHooks #Bootstrap",
  },
  {
    name: "Social App",
    github: "https://github.com/koftov/merng-client",
    url: "https://kofbook.netlify.app/",
    show: false,
    description:
      "Social app using React hooks & context with GraphQL server and MongoDB",
    tags: "#MongoDB #Express #Node #React #GraphQL #SemanticUI",
  },
  {
    name: "Shopping List",
    github: "https://github.com/koftov/shoppinglist",
    url: "https://koftovshoppinglist.herokuapp.com/",
    show: false,
    description:
      "Shopping List built with MERN and Redux and JWT authentication",
    tags: "#MongoDB #Express #Node #React #Redux #PWA",
  },
  {
    name: "Furniture Store",
    github: "https://github.com/koftov/furniture-store",
    url: "https://koftovstore.herokuapp.com/",
    show: false,
    description: "Next JS store app using semantic ui and stripe",
    tags: "#NextJS #SemanticUI #Stripe",
  },
  {
    name: "IT Logger",
    github: "https://github.com/koftov/it-logger",
    url: "https://koftovitlogger.herokuapp.com/",
    show: false,
    description:
      "React app using Redux to track IT dept issues with JSON server",
    tags: "#React #Redux #JsonServer #Materialize",
  },
  {
    name: "Weather",
    github: "https://github.com/koftov/weather",
    url: "https://wweather.netlify.app/",
    show: false,
    description: "React & Redux wether app",
    tags: "#React #Redux #SemanticUI #Redux-Thunk #PWA",
  },
  {
    name: "Story Books",
    github: "https://github.com/koftov/storybooks",
    url: "http://koftovstorybooks.herokuapp.com/",
    show: false,
    description: "Node.js app with Google OAuth",
    tags: "#MongoDB #EJS #Express #Node #OAuth #Passport",
  },
  {
    name: "Expense Tracker",
    github: "https://github.com/koftov/expense-tracker",
    url: "https://koftovexpensetracker.herokuapp.com",
    show: false,
    description:
      "Full Stack Expense tracker using React hooks & context with Express server and MongoDB",
    tags: "#MongoDB #Express #Node #React #ContextAPI",
  },
  {
    name: "Koftov Plan",
    github: "https://github.com/koftov/koftovplan",
    url: "https://koftovsplan.web.app/",
    show: false,
    description:
      "A simple Project Management Web Application using React, Redux and Firebase.",
    tags: "#Firebase #Firestore #React #Redux #PWA",
  },
  {
    name: "Hunt",
    github: "https://github.com/koftov/hunt",
    url: "https://koftov-hunt.web.app",
    show: false,
    description: "Product hunt clone using ionic-react",
    tags: "#Ionic #Firebase #Firestore #Firebase-Storage #React #PWA",
  },
  {
    name: "Links",
    github: "https://github.com/koftov/koftov-links",
    url: "https://koftov-links.web.app",
    show: false,
    description:
      "Hacker News clone using ionic-react and firebase and firestore",
    tags: "#Ionic #Firebase #Firestore #React #PWA",
  },
  {
    name: "React Firebase Chat",
    github: "https://github.com/koftov/reactfirebasechat",
    url: "http://koftovreactchat.web.app/",
    show: false,
    description: "Realtime chat app with react and firebase",
    tags: "#React #Firebase #Firestore",
  },
  {
    name: "Netflix",
    github: "https://github.com/koftov/netflix",
    url: "http://koftov-netflix.web.app/",
    show: false,
    description:
      "Netflix clone built with react and firebase using styled-components",
    tags: "#React #Firebase #Firestore #Styled-Components",
  },
  {
    name: "Devmeetups",
    github: "https://github.com/koftov/devmeetups",
    url: "https://devmeetupz.web.app",
    show: false,
    description:
      "A full stack meetups app using Vue, Vuex, Veutify and Firebase server",
    tags: "#Firebase #Firestore #Vue #Vuetify",
  },
  {
    name: "Geo Apes",
    github: "https://github.com/koftov/geo-apes",
    url: "https://geo-apes.web.app",
    show: false,
    description:
      "A full stack app to track other friends around the globe using google maps API and firebase backend",
    tags: "#Firebase #Firestore #Vue #Materialize",
  },
  {
    name: "Employee Manager",
    github: "https://github.com/koftov/employee-manager",
    url: "https://vue-koftov.web.app/",
    show: false,
    description: "Employee manager app built on Vue.js and FireStore",
    tags: "#Firebase #Firestore #Vue #Materialize",
  },
  {
    name: "Koftov Smoothies",
    github: "https://github.com/koftov/koftov-smoothies",
    url: "https://koftov-smoothies.web.app",
    show: false,
    description:
      "A simple CRUD project to learn the basics of vue, using firebase/firestore",
    tags: "#Firebase #Firestore #Vue #Materialize",
  },
  {
    name: "Koftov Chat",
    github: "https://github.com/koftov/koftovchat",
    url: "https://koftovchat.web.app",
    show: false,
    description: "VueJS & firebase realtime chat",
    tags: "#Firebase #Firestore #Vue #Materialize",
  },
  {
    name: "Corona Crm",
    github: "https://github.com/koftov/corona-crm",
    url: "https://coronacrm.netlify.app/",
    show: false,
    description:
      "An app to track customers using vanilla js, Express server and MongoDB",
    tags: "#MongoDB #Express #Node #VanilaJS #Bootstrap",
  },
  {
    name: "Search Github Users",
    github: "https://github.com/koftov/react-search-github-users",
    url: "https://ghuserssearch.netlify.app/",
    show: false,
    description:
      "A react app to search for github users using fusioncharts and auth0",
    tags: "#Auth0 #FusionCharts #React",
  },
  {
    name: "Github Finder",
    github: "https://github.com/koftov/githubfinder",
    url: "https://ggithubfinder.netlify.app/",
    show: false,
    description: "Search Github users - React hooks & context",
    tags: "#React #ContextAPI #ReactHooks #Bootstrap #PWA",
  },
  {
    name: "Github Jobs",
    github: "https://github.com/koftov/github-jobs",
    url: "https://koftovgithubjobs.netlify.app/",
    show: false,
    description: "Search Github jobs",
    tags: "#React #ReactHooks #ReactBootstrap",
  },
  {
    name: "Hacker News",
    github: "https://github.com/koftov/hacker-news",
    url: "https://hacker-new.netlify.app/",
    show: false,
    description: "Hacker News clone",
    tags: "#React #ReactHooks #Axios #HackerNews",
  },
  {
    name: "Image finder",
    github: "https://github.com/koftov/pixabay-image-finder",
    url: "https://koftovimgfinder.netlify.app/",
    show: false,
    description: "React & Material UI image finder app using Pixabay API",
    tags: "#React #MaterialUI",
  },
  {
    name: "Lyric finder",
    github: "https://github.com/koftov/lyricfinder",
    url: "https://koftovlyricfinder.netlify.app/",
    show: false,
    description:
      "App that finds song lyrics using React and the Musixmatch API",
    tags: "#React #Bootstrap",
  },
  {
    name: "BMI Calculator",
    github: "https://github.com/koftov/ionic-react-bmi-calculator",
    url: "https://koftovbmi.netlify.app/",
    show: false,
    description: "Simple BMI calculator build with ionic and react",
    tags: "#React #Ionic",
  },
  {
    name: "Movies",
    github: "https://github.com/koftov/koftov-movies",
    url: "https://koftov-movies.netlify.app/",
    show: false,
    description: "React movies app using themoviedb API",
    tags: "#React",
  },
  {
    name: "Breaking Bad Cast",
    github: "https://github.com/koftov/breaking-bad-cast",
    url: "https://koftov.github.io/breaking-bad-cast/",
    show: false,
    description: "React app to show cast info for breaking bad",
    tags: "#React",
  },
  {
    name: "Giphy",
    github: "https://github.com/koftov/giphy",
    url: "https://koftov.github.io/giphy",
    show: false,
    description: "React app using Giphy API",
    tags: "#React",
  },
  {
    name: "Coinstar",
    github: "https://github.com/koftov/cryptocurrency-tracker",
    url: "https://koftovcoinstar.netlify.app/",
    show: false,
    description: "Cryptocurrency tracker",
    tags: "#React #ChartJS",
  },
  {
    name: "React Colors",
    github: "https://github.com/koftov/react-colors",
    url: "https://koftovreactcolors.netlify.app/",
    show: false,
    description: "React colors picker app using material-ui",
    tags: "#React #MaterialUI",
  },
  {
    name: "Album Store",
    github: "https://github.com/koftov/album-store",
    url: "https://albumstore.netlify.app",
    show: false,
    description: "React store app using context api, bootstrap and paypal",
    tags: "#React #Redux #PayPal",
  },
  {
    name: "Chuck Norris Jokes",
    github: "https://github.com/koftov/chucknorrisjokes",
    url: "https://koftov.github.io/chucknorrisjokes",
    show: false,
    description:
      "React app fetched to chuck norris jokes API with uses react hookes and material-ui",
    tags: "#React #MaterialUI",
  },
];
